class Constants {
    val WEB_DEVELOPMENT_FILE_TYPES = mapOf(
        ".ai" to "Adobe Illustrator",
        ".asp" to "ASP Classic",
        ".aspx" to "ASP.NET",
        ".ai" to "Adobe Illustrator",
        ".babelrc" to "Babel",
        ".bat" to "Batch Script",
        ".bmp" to "Bitmap Image",
        ".cs" to "C#",
        ".cpp" to "C++",
        ".css" to "CSS",
        ".csv" to "CSV",
        ".conf" to "Config",
        ".cs" to "NUnit",
        ".cpp" to "C++",
        ".doc" to "Document",
        ".dart" to "Dart",
        ".Dockerfile" to "Docker",
        ".json" to "ESLint",
        ".exe" to "Executable",
        ".flac" to "Audio",
        ".liquid" to "Flask",
        ".gif" to "GIF",
        ".go" to "Go",
        ".groovy" to "Groovy",
        ".groovy" to "Grails",
        ".graphql" to "GraphQL",
        ".html" to "HTML",
        ".html" to "Django",
        ".html" to "Flask",
        ".java" to "Hibernate",
        ".java" to "Java",
        ".jsp" to "JavaServer Pages",
        ".js" to "JavaScript",
        ".java" to "JUnit",
        ".java" to "Selenium",
        ".jsx" to "Js Test",
        ".jpg" to "Image",
        ".java" to "Hibernate",
        ".json" to "JSON",
        ".java" to "Java",
        ".jar" to "Java Archive",
        ".js" to "JavaScript",
        ".json" to "JSON",
        ".jsp" to "JavaServer Pages",
        ".mk" to "Makefile",
        ".md" to "Markdown",
        ".mp3" to "Audio",
        ".mp4" to "Video",
        ".m" to "Objective-C",
        ".md" to "Markdown",
        ".mk" to "Makefile",
        ".php" to "PHP",
        ".pdo" to "PHP Data Object",
        ".php" to "PHPUnit",
        ".pl" to "Perl",
        ".ps1" to "Windows PowerShell",
        ".ppt" to "Presentation",
        ".psd" to "Adobe Photoshop Document",
        ".py" to "Python"
    )
}